# Generated by Django 4.1.3 on 2022-12-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movieorder",
            old_name="buyed_movie",
            new_name="movie",
        ),
    ]
